{{- if .Values.wallarm.enabled -}}
apiVersion: v1
data:
  token: {{ .Values.wallarm.token | b64enc | quote }}
kind: Secret
metadata:
  name: {{ template "wallarm.token.name" . }}
  labels:
    {{- include "kong.metaLabels" . | nindent 4 }}
    app.kubernetes.io/component: wallarm-controller
type: Opaque
{{- end }}
